### ISSUE TITLE
Capture 404s and AJAX errors

### ISSUE THREAD

**Issue by taitems** [skroonenburg/Appfail-JavaScript#10]
It's one thing for AppFail server components (.NET etc) to capture 404s, but what if the page is requesting off-site resources (JS/CSS)? It would be great if we could capture 404s etc as well as failed XHR requests.

It's not possible to handle CORS as that's strictly browser only.

`navigator.onLine` is relevant here in helping filter the relevance of these errors.

**Comment by skroonenburg** [comment]
Yes 404s would be massive.

Even better: if I encounter a JS error I want to know context about other things that have failed that may have caused it.
So rather than capturing 404s as separate errors we could log them along with the javascript exception. Then in the Appfail dashboard we could surface something like:

Error: Function not defined obj.jqGrid()
Filename, line number

Resource loading errors on this page:    jquery.jqgrid.min.js was not found.

Ie. It shows you the symptom & let's you deduce the cause.

**Comment by taitems** [comment]
Colour me aroused.

**Comment by skroonenburg** [comment]
Sexy. Done.
